### ISSUE TITLE
Fails to create tmp directory on WSL

### ISSUE THREAD

**Issue by villasv** [GoogleChrome/chrome-launcher#188] opened 2020-02-03 21:26 UTC
#### Provide the steps to reproduce
1. Run LH inside WSL2
  
#### What is the current behavior?
```
Runtime error encountered: EACCES: permission denied, mkdir '/mnt/undefined'
Error: EACCES: permission denied, mkdir '/mnt/undefined'
    at Object.mkdirSync (fs.js:750:3)
    at sync (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/mkdirp/index.js:71:13)
    at sync (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/mkdirp/index.js:77:24)
    at sync (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/mkdirp/index.js:77:24)
    at sync (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/mkdirp/index.js:77:24)
    at sync (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/mkdirp/index.js:77:24)
    at Function.sync (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/mkdirp/index.js:77:24)
    at makeWin32TmpDir (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/utils.js:115:12)
    at Object.makeTmpDir (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/utils.js:85:20)
    at Launcher.makeTmpDir (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:115:24)
```

#### What is the expected behavior?
No error.

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 5.6.0
* Chrome version:
* Node.js version: 10.14.1
* Operating System: Ubuntu on Windows 10 WSL2

**Comment by michaelchiche** [comment] 2020-02-06 23:43
I am also having a problem with lighthouse inside WSL2.

It opens the chrome browser but then hangs with:

![image](https://user-images.githubusercontent.com/371278/73988373-c92c1500-4942-11ea-8354-4cdba539fafe.png)


It looks like lighthouse succeeds to open chrome but cant seem to connect and manage it

**Comment by G-Rath** [comment] 2020-04-06 09:28
> It's pretty common nowadays to configure WSL not to append the Windows PATH to the Linux PATH because it slows everything down SO MUCH

I don't know about that, but in my case I get this issue because I have my C:\ mounts in `/c/` instead of `/mnt/c/`, which is required due a bug in docker.

Ultimately the most stable fix is probably to call `wslpath "C:\"` at the top level once you know it's WSL.

**Comment by G-Rath** [comment] 2020-05-14 22:53
@paulirish @patrickhulce I'm now very interested in getting this fixed in `chrome-launcher` ideally asap so it can get into `lighthouse` asap.

I've confirmed that `chrome-launcher` successfully launches a new "blank slate" Chrome without issue in WSL after I remove all the `/mnt/`s (since my C is mounted in `/c/`), so I think this is the only thing missing for WSL right now.

I'm happy to do PRs, but wanted to get some input on what solution you'd be happy with.

The ideal solution would be to use a utility function like this:

```
const wslPath = str => child_process.execSync(`wslpath -u ${str}`).toString().trim();
```

(overall, this should be taken a step further by refactoring the existing `toWinDirFormat` and then calling it in a few more places)

I think this solution is good: it's a very fast command, and saves a bunch of edge-case support.
The downside is there's not a particularly nice way to test it, if that matters for you.

I'll open a PR for this soon, but posting here in case you have initial thoughts.

**Comment by patrickhulce** [comment] 2020-05-14 23:19
SGTM @G-Rath thanks for your help! We should avoid any string interpolation from string commands though, opting for `execFile` and passing as arguments instead. (#199 mistakenly believes we do this already but we certainly shouldn't start 😄)

FWIW there shouldn't be any sequencing issues with Lighthouse dependency here, publishing a fix should be enough for new installs and folks to be able to update their lockfiles since it uses a loose `^0.13.2` dependency.

**Comment by G-Rath** [comment] 2020-05-14 23:26
>  since it uses a loose ^0.13.2 dependency

So long as it's a bug release yeah - if its a minor release it won't be allowed because it's `0.x.x`,

**Comment by patrickhulce** [comment] 2020-05-14 23:46
> publishing a *fix*

> So long as it's a bug release yeah

ya, that's the plan ;)

**Comment by G-Rath** [comment] 2020-05-14 23:47
@patrickhulce unfortunately the current release of `lighthouse` depends on `^0.11.2` :(

**Comment by patrickhulce** [comment] 2020-05-15 00:30
@G-Rath the 6.0 release was just cut yesterday and is being published to npm Monday that uses 0.13.2 :)

You could also use `6.0.0-beta.0` today which I *think* might be on `0.13.1`?

**Comment by G-Rath** [comment] 2020-05-15 00:34
> the 6.0 release was just cut yesterday

🥳 you just made my day, as that will hopefully let us address the audit reports (I've not checked it out, but seen the dependencies being reported are flagged, so fingers crossed).

The beta is using `0.13.x` - I remember seeing the PR; I'll check it today if I have the time but otherwise use v6 on Monday 🥳🎉

**Comment by wschaef** [comment] 2020-08-26 14:35
The issue is still there. I'm using the version 0.13.4. 
The Problem is that the code asumes, that in the PATH there is an entry like:

`/mnt/c/Users/YOREUSERNAME/AppData/`

otherwise userRegExp does not match:

```javascript
function getLocalAppDataPath(path) {
    const userRegExp = /\/mnt\/([a-z])\/Users\/([^\/:]+)\/AppData\//;
```
Solution is: just handle wsl like linux

```javascript
function makeTmpDir() {
    switch (getPlatform()) {
        case 'darwin':
        case 'linux':
            return makeUnixTmpDir();
        case 'wsl':
            return makeUnixTmpDir();
```

Dirty workaround until it is fixed:
just put 

`/mnt/c/Users/YOREUSERNAME/AppData/`

in you path

**Comment by villasv** [comment] 2020-08-26 15:52
I agree with @wschaef. Is there any reason why not to handle WSL just like linux?

**Comment by patrickhulce** [comment] 2020-08-26 16:05
I thought there were issues with using a user-data-dir in `/tmp` but a Chrome in `/mnt/c/`, but I could be wrong my WSL experience is extremely limited. I'm certainly in for doing this as a fallback at the least 👍 

If our active WSL users are doing this as a workaround already, then maybe it's safe by default too?

**Comment by nowlena** [comment] 2020-09-13 15:55
> The issue is still there. I'm using the version 0.13.4.
> The Problem is that the code asumes, that in the PATH there is an entry like:
> 
> `/mnt/c/Users/YOREUSERNAME/AppData/`
> 
> otherwise userRegExp does not match:
> 
> ```js
> function getLocalAppDataPath(path) {
>     const userRegExp = /\/mnt\/([a-z])\/Users\/([^\/:]+)\/AppData\//;
> ```
> 
> Solution is: just handle wsl like linux
> 
> ```js
> function makeTmpDir() {
>     switch (getPlatform()) {
>         case 'darwin':
>         case 'linux':
>             return makeUnixTmpDir();
>         case 'wsl':
>             return makeUnixTmpDir();
> ```
> 
> Dirty workaround until it is fixed:
> just put
> 
> `/mnt/c/Users/YOREUSERNAME/AppData/`
> 
> in you path

Was having same issue, the quoted comment is what allowed me to make a quick fix.

ie. updating the `makeTmpDir` utils fn to read:

```js
function makeTmpDir() {
    switch (getPlatform()) {
        case 'darwin':
        case 'linux':
        case 'wsl':
            return makeUnixTmpDir();
        case 'win32':
            return makeWin32TmpDir();
        default:
            throw new UnsupportedPlatformError();
    }
}
```

**Comment by nosvalds** [comment] 2022-03-09 15:17
This is still an issue. I just ran into this trying to use chrome-launcher and Lighthouse on an Azure Function that runs on Linux.

## Error

```
Error: EACCES: permission denied, mkdir '/mnt/undefined/Users/undefined/AppData/Local/lighthouse.39468148'
    at Object.mkdirSync (fs.js:1013:3)
    at makeWin32TmpDir (/home/site/wwwroot/node_modules/chrome-launcher/dist/utils.js:106:10)
    at Object.makeTmpDir (/home/site/wwwroot/node_modules/chrome-launcher/dist/utils.js:76:20)
    at Launcher.makeTmpDir (/home/site/wwwroot/node_modules/chrome-launcher/dist/chrome-launcher.js:134:24)
    at Launcher.prepare (/home/site/wwwroot/node_modules/chrome-launcher/dist/chrome-launcher.js:141:53)
    at Launcher.launch (/home/site/wwwroot/node_modules/chrome-launcher/dist/chrome-launcher.js:192:18)
    at Object.launch (/home/site/wwwroot/node_modules/chrome-launcher/dist/chrome-launcher.js:37:20)
    at runLighthouse (/home/site/wwwroot/metrics/google.js:30:41)
    at /home/site/wwwroot/metrics/google.js:56:29
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/mnt/undefined/Users/undefined/AppData/Local/lighthouse.39468148'
}
```

## Info

process.platform -> "linux"
os.release() -> 5.4.81-microsoft-standard
os.platform() -> linux
cat /proc/version -> Linux version 5.4.81-microsoft-standard (oe-user@oe-host) (gcc version 9.3.0 (GCC)) #1 SMP Thu Dec 3 23:47:24 UTC 2020

**Comment by connorjclark** [comment] 2022-03-10 01:32
Would someone like to send us a patch that does the fix outlined here? https://github.com/GoogleChrome/chrome-launcher/issues/188#issuecomment-691689080

@nosvalds can you verify that fix works for you too?

**Comment by nosvalds** [comment] 2022-03-10 10:19
Hey @connorjclark I was not able to get the fix you reference to work in my case. I wouldn't say I disproved it as a viable option though. I've actually abandoned Azure Functions/WSL as my use case will work just fine in a GitHub Action workflow on Ubuntu.

**Comment by connorjclark** [comment] 2022-03-11 01:21
Ah too bad, but thanks for checking.

**Comment by G-Rath** [comment] 2022-03-11 01:28
@connorjclark I believe #200 should fix this

**Closed** 2022-03-14 22:29 UTC
